"""rename department

Revision ID: 689954b00f9b
Revises: 6c16d8e03e95
Create Date: 2025-08-31 18:04:06.716323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '689954b00f9b'
down_revision = '6c16d8e03e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
